[common]
"autoconf"
"ca-certificates"
"gcc"
"btop"
"git"
"git-flow-avh"
"cloudflared"
"docker"
"docker-compose"
"exa"
"fzf"
"pinentry"
"pyenv"
"stow"
"syncthing"
"texlive"
"tmux"
"tree"
"wget"
"zoxide"
"zsh"
"zsh-autosuggestions"
"zsh-completions"
"zsh-syntax-highlighting"

[macos]
"gnutls"
"gnupg"
"pinentry-mac"