- name: Bootstrap development environment
  hosts: localhost
  gather_facts: yes
  
  tasks:
    - name: Install Additional Packages for MacOS
      # become: yes
      ansible.builtin.package:
        name:
          - "espanso"
          - "kitty"
          - "zoxide"
        state: "present"
  


# References
# [1] https://phelipetls.github.io/posts/introduction-to-ansible/