- name: Bootstrap development environment
  hosts: localhost
  gather_facts: yes
            
  tasks:
  - name: Install OS packages
    become: yes
    ansible.builtin.package:
      name:
        - bat
        - fzf
        - git
        - stow
        - tmux
      state: present
    
  - name: Clone dotfiles to home directory
    ansible.builtin.git:
      repo: "https://github.com/hsteinshiromoto/dotfiles.linux.git"
      dest: "{{ ansible_env.HOME }}/dotfiles"

  - name: Stow dotfiles 
    ansible.builtin.shell:
      cmd: "cd $HOME/dotfiles && stow ."
