- name: Bootstrap development environment
  hosts: localhost
  gather_facts: yes
  vars:
    dotfiles_git_repository: "git@github.com:hsteinshiromoto/dotfiles.linux.git"
    dotfiles_dir: "{{ ansible_env.HOME }}/dotfiles"
             
  tasks:
  - name: Install packages with apt
    become: yes
    ansible.builtin.apt:
      name:
        - fzf
        - git
        - stow
        - tmux
      state: present
    when: ansible_distribution == "Ubuntu"

  - name: Clone dotfiles to home directory
    ansible.builtin.git:
      repo: "{{ dotfiles_git_repository }}"
      dest: "{{ dotfiles_dir }}"

  - name: Stow dotfiles 
    ansible.builtin.shell:
      cmd: "stow $HOME/dotfiles"
