- name: Bootstrap development environment
  hosts: localhost
  gather_facts: yes
  vars:
    should_be_root:  "{{ true if ansible_pkg_mgr != 'brew' else false }}"
    dotfiles_dir: "{{ ansible_env.HOME }}/dotfiles"
            
  tasks:
    - name: Install Homebrew
      when: ansible_facts['os_family'] == "Darwin"
      ansible.builtin.shell:
        cmd: '/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"'

    - name: Install OS packages
      become: "{{ should_be_root }}"
      ansible.builtin.package:
        update_cache: yes
        name:
          - bat
          - btop
          - curl
          - exa
          - fzf
          - git
          - git-flow
          - gpg
          - mc
          - stow
          - tmux
          - vim
          - zsh
          - zsh-autosuggestions
          - zsh-syntax-highlighting
        state: present

    - name: Install LazyDocker
      ansible.builtin.shell:
        cmd: "curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash"

    #- name: Install LazyGit
      #ansible.builtin.shell:
        #  cmd: "bash bin/install_lazygit.sh"

    - name: Install NVIm
      import_tasks: roles/nvim.yml

    - name: Install MacOS Packages
      import_tasks: roles/macosx.yml
   
# References
#
# [1] https://stackoverflow.com/questions/63242221/use-ansible-package-module-to-work-with-apt-and-homebrew 
