- name: Bootstrap development environment
  hosts: localhost
  gather_facts: yes
  vars:
    should_be_root:  "{{ true if ansible_pkg_mgr != 'brew' else false }}"
            
  tasks:
  - name: Install OS packages
    become: "{{ should_be_root }}"
    ansible.builtin.package:
      name:
        - bat
        - btop
        - curl
        - fzf
        - git
        - git-flow
        - gpg
        - mc
        - stow
        - tmux
        - vim
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
      state: present

  - name: Install LazyDocker
    ansible.builtin.shell:
      cmd: "curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash"

  - name: Install LazyGit
    ansible.builtin.shell:
      cmd: "bash bin/install_lazygit.sh"

  - name: Install Eza
    ansible.builtin.shell:
      cmd: "bash bin/install_eza.sh"

  - name: Install VIm Plugins
    import_tasks: roles/vim.yml

  - name: Install MacOS Packages
    import_tasks: roles/macosx.yml
   
# References
#
# [1] https://stackoverflow.com/questions/63242221/use-ansible-package-module-to-work-with-apt-and-homebrew 
