- name: Bootstrap development environment
  hosts: localhost
  gather_facts: yes
            
  tasks:
  - name: Install OS packages
    become: yes
    ansible.builtin.package:
      name:
        - bat
        - btop
        - curl
        - fzf
        - git
        - git-flow
        - gpg
        - mc
        - stow
        - tmux
        - vim
        - zsh
        - zsh-autosuggestions
        - zsh-syntax-highlighting
      state: present

  - name: Install LazyDocker
    ansible.builtin.shell:
      cmd: "curl https://raw.githubusercontent.com/jesseduffield/lazydocker/master/scripts/install_update_linux.sh | bash"

  - name: Install LazyGit
    ansible.builtin.shell:
      cmd: "bash bin/install_lazygit.sh"

  - name: Install Eza
    ansible.builtin.shell:
      cmd: "bash bin/install_eza.sh"

  - name: Install VIm Plugins
    import_tasks: roles/vim.yml

  - name: Install MacOS Packages
    import_tasks: roles/macosx.yml
    
