- name: Set Variables
  set_fact:
    nvim_dir: "{{ ansible_env.HOME }}/.config/nvim"

- name: Ensure nvim config directory exist
  loop:
    - "{{ nvim_dir }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    recurse: no
      
- name: Install nvim
  ansible.builtin.shell: |
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    sudo rm -rf /opt/nvim
    sudo tar -C /opt -xzf nvim-linux64.tar.gz

- name: Install Rust
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  
- name: Configure to use cargo (for ZSH only the first line is needed)
  ansible.builtin.shell: . {{ ansible_env.HOME }}/.cargo/env

- name: Install treesitter-cli using cargo
  ansible.builtin.shell: cargo install tree-sitter-cli | sh -s -- -y

# References:
#   [1] https://www.redhat.com/sysadmin/ansible-configure-vim
#   [2] https://github.com/junegunn/vim-plug/issues/730
