- name: Set Variables
  set_fact:
    nvim_dir: "{{ ansible_env.HOME }}/.config/nvim"
    init: "{{ ansible_env.HOME }}/.config/nvim/init"

- name: Ensure nvim config directory exist
  loop:
    - "{{ nvim_dir }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: 0750
    recurse: no
      
- name: Install nvim
  ansible.builtin.shell: |
    curl -LO https://github.com/neovim/neovim/releases/latest/download/nvim-linux64.tar.gz
    sudo rm -rf /opt/nvim
    sudo tar -C /opt -xzf nvim-linux64.tar.gz
    echo 'export PATH="$PATH:/opt/nvim-linux64/bin"' >> {{ ansible_env.HOME }}/.zshrc

- name: Install Rust
  ansible.builtin.shell: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
  
- name: Configure ZSH to use cargo
  ansible.builtin.shell: |
    . {{ ansible_env.HOME }}/.cargo/env
    printf '#!/bin/sh\nexport CARGO_HOME=/opt/cargo\nexec /bin/sh "$@"\n' >/usr/local/bin/sh
    chmod +x /usr/local/bin/sh

- name: Install treesitter-cli using cargo
  ansible.builtin.shell: cargo install -y tree-sitter-cli

# References:
#   [1] https://www.redhat.com/sysadmin/ansible-configure-vim
#   [2] https://github.com/junegunn/vim-plug/issues/730
