"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#7aa2f7)\
$os\
[](fg:#7aa2f7 bg:#15161e)\
[](fg:#15161e bg:#24293b)\
$username\
[](fg:#24293b bg:#15161e)\
[](fg:#15161e bg:#24293b)\
$shell\
[](fg:#24293b bg:#15161e)\
[](fg:#15161e bg:#24293b)\
$directory\
[](fg:#24293b bg:#15161e)\
[](fg:#15161e bg:#24293b)\
$git_branch\
[ ](fg:#7aa2f7 bg:#24293b)\
$git_status\
[](fg:#24293b bg:#15161e)\
[](fg:#15161e bg:#1d2230)\
$time\
[](fg:#1d2230)\
\n$character"""


[os]
disabled = false
style = "fg:#15161e bg:#7aa2f7"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[username]
show_always = true
style_user = "fg:#7aa2f7 bg:#24293b"
style_root = "bg:#24293b fg:#f7768e"
format = '[ $user ]($style)'

[directory]
style = "fg:#73daca bg:#24293b"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#24293b"
format = '[[ $symbol $branch ](fg:#9ece6a bg:#24293b)]($style)'

[git_status]
style = "bg:#24293b"
format = '[[($all_status$ahead_behind )](fg:#e0af68 bg:#24293b)]($style)'

[shell]
disabled = false
style = "bg:#24293b"
bash_indicator = "$"
zsh_indicator = "zsh"
format = '[[ $indicator ](fg:#2ac3de bg:#24293b)]($style)'
fish_indicator = "fish"
powershell_indicator = "psh"
ion_indicator = "ion"
elvish_indicator = "esh"
tcsh_indicator = "tsh"
xonsh_indicator = "xsh"
cmd_indicator = "cmd"
nu_indicator = "nu"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#1d2230"
format = '[[  $time ](fg:#7aa2f7 bg:#1d2230)]($style)'

[character]
disabled = false
success_symbol = '[I:](bold fg:#7aa2f7)'
error_symbol = '[I:](bold fg:#f7768e)'
vimcmd_symbol = '[N:](bold fg:#7aa2f7)'
