"$schema" = 'https://starship.rs/config-schema.json'

format = """
[░▒▓](#7aa2f7)\
$os\
[  ](bold bg:#7aa2f7 fg:#24293b)\
$hostname\
[](fg:#7aa2f7 bg:#15161e)\
[](fg:#15161e bg:#24293b)\
$username\
[](fg:#24293b bg:#15161e)\
[](fg:#15161e bg:#2d2a2d)\
$shell\
[](fg:#2d2a2d bg:#15161e)\
[](fg:#15161e bg:#262d2d)\
$directory\
[](fg:#262d2d bg:#15161e)\
[](fg:#15161e bg:#1b2c31)\
$git_branch\
[ ](fg:#1bbc9b bg:#1b2c31)\
$git_status\
[](fg:#1b2c31 bg:#15161e)\
[](fg:#15161e bg:#2b283b)\
$time\
[](fg:#2b283b)\
\n$character"""


[os]
disabled = false
style = "fg:#15161e bg:#7aa2f7"
format = "[ $symbol]($style)"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
NixOS = "󱄅"

[username]
show_always = true
style_user = "fg:#7aa2f7 bg:#24293b"
style_root = "bg:#24293b fg:#f7768e"
format = '[ @$user ]($style)'

[directory]
style = "fg:#9ece6a bg:#262d2d"
format = "[    $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[git_branch]
symbol = ""
style = "bg:#1b2c31"
format = '[[ $symbol $branch ](fg:#1bbc9b bg:#1b2c31)]($style)'

[git_status]
style = "bg:#1b2c31"
format = '[[($all_status$ahead_behind )](fg:#1bbc9b bg:#1b2c31)]($style)'

[hostname]
ssh_only = false
format = '[$hostname ]($style)'
style = "bold bg:#7aa2f7 fg:#24293b"
trim_at = '.local'
disabled = false

[shell]
disabled = false
style = "bg:#2d2a2d"
bash_indicator = "$"
zsh_indicator = "zsh"
format = '[[    $indicator ](fg:#e0af69 bg:#2d2a2d)]($style)'
fish_indicator = "fish"
powershell_indicator = "psh"
ion_indicator = "ion"
elvish_indicator = "esh"
tcsh_indicator = "tsh"
xonsh_indicator = "xsh"
cmd_indicator = "cmd"
nu_indicator = "nu"

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#2b283b"
format = '[[    $time ](fg:#bb9af7 bg:#2b283b)]($style)'

[character]
disabled = false
success_symbol = '[I:](bold fg:#7aa2f7)'
error_symbol = '[I:](bold fg:#f7768e)'
vimcmd_symbol = '[N:](bold fg:#7aa2f7)'
