# Window [2]
bind | split-window -h
bind - split-window -v
unbind '"'
unbind %

# reload config file (change file location to your the tmux.conf you want to use) [2]
bind r source-file ~/.tmux.conf

# Enable mouse mode (tmux 2.1 and above) [2,4]
set -g mouse on

# switch panes using Alt-arrow without prefix [2]
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D

# Weather [3]
set -g status-interval 60
WEATHER='#(curl -s wttr.in/Sydney\?format\="%%l:+%%c%%20%%t%%60%%w&period=60")'
set -g status-right "$WEATHER ..."

# References 

# [1] https://gist.github.com/michaellihs/b6d46fa460fa5e429ea7ee5ff8794b96
# [2] https://www.hamvocke.com/blog/a-guide-to-customizing-your-tmux-conf/
# [3] https://github.com/chubin/wttr.in#one-line-output
# [4] https://superuser.com/questions/209437/how-do-i-scroll-in-tmux
